<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $equipment = [
            [
                'name' => 'Shoulder Press Machine',
                'category' => 'Machines',
                'brand' => 'Technogym',
                'model' => 'SP-900',
                'serial_number' => 'AUX-EQ-0001',
                'location' => 'Strength Zone',
                'primary_muscle_group' => 'Shoulders',
                'secondary_muscle_group' => 'Triceps',
                'supported_level' => 'All Levels',
                'linked_exercises' => 12,
                'purchase_price' => 3500000,
                'status' => 'Active',
                'maintenance_priority' => 'Low',
                'description' => 'Seated shoulder press machine for controlled overhead pressing.',
                'safety_instructions' => 'Adjust the seat before use and keep the back against the pad.',
            ],
            [
                'name' => 'Leg Press Machine',
                'category' => 'Machines',
                'brand' => 'Life Fitness',
                'model' => 'LP-700',
                'serial_number' => 'AUX-EQ-0002',
                'location' => 'Lower Body Zone',
                'primary_muscle_group' => 'Legs',
                'secondary_muscle_group' => 'Glutes',
                'supported_level' => 'All Levels',
                'linked_exercises' => 9,
                'purchase_price' => 4800000,
                'status' => 'Active',
                'maintenance_priority' => 'Low',
                'description' => 'Plate-loaded leg press machine for lower body strength training.',
                'safety_instructions' => 'Lock the safety handles before entering or leaving the machine.',
            ],
            [
                'name' => 'Lat Pulldown Machine',
                'category' => 'Machines',
                'brand' => 'Hammer Strength',
                'model' => 'LPD-500',
                'serial_number' => 'AUX-EQ-0003',
                'location' => 'Back Zone',
                'primary_muscle_group' => 'Back',
                'secondary_muscle_group' => 'Biceps',
                'supported_level' => 'Beginner',
                'linked_exercises' => 15,
                'purchase_price' => 2700000,
                'status' => 'Maintenance',
                'maintenance_priority' => 'Medium',
                'description' => 'Cable machine for lat pulldown and upper back variations.',
                'safety_instructions' => 'Inspect the cable and attachment before use.',
            ],
            [
                'name' => 'Dumbbells Set',
                'category' => 'Free Weights',
                'brand' => 'Rogue',
                'model' => 'Hex 2.5-50kg',
                'serial_number' => 'AUX-EQ-0004',
                'location' => 'Free Weight Area',
                'primary_muscle_group' => 'Full Body',
                'secondary_muscle_group' => 'None',
                'supported_level' => 'All Levels',
                'linked_exercises' => 48,
                'purchase_price' => 6200000,
                'status' => 'Active',
                'maintenance_priority' => 'Low',
                'description' => 'Rubber hex dumbbell set for strength and accessory exercises.',
                'safety_instructions' => 'Return dumbbells to the rack after use and avoid dropping them.',
            ],
            [
                'name' => 'Treadmill Pro',
                'category' => 'Cardio',
                'brand' => 'NordicTrack',
                'model' => 'Commercial 2450',
                'serial_number' => 'AUX-EQ-0005',
                'location' => 'Cardio Deck',
                'primary_muscle_group' => 'Legs',
                'secondary_muscle_group' => 'Core',
                'supported_level' => 'All Levels',
                'linked_exercises' => 6,
                'purchase_price' => 3900000,
                'status' => 'Active',
                'maintenance_priority' => 'Medium',
                'description' => 'Commercial treadmill for walking, jogging and interval running.',
                'safety_instructions' => 'Attach the safety clip before starting high-speed sessions.',
            ],
            [
                'name' => 'Adjustable Bench',
                'category' => 'Benches',
                'brand' => 'Body-Solid',
                'model' => 'FID-46',
                'serial_number' => 'AUX-EQ-0006',
                'location' => 'Free Weight Area',
                'primary_muscle_group' => 'Chest',
                'secondary_muscle_group' => 'Shoulders',
                'supported_level' => 'All Levels',
                'linked_exercises' => 22,
                'purchase_price' => 850000,
                'status' => 'Active',
                'maintenance_priority' => 'Low',
                'description' => 'Flat, incline and decline bench for pressing and accessory exercises.',
                'safety_instructions' => 'Confirm the adjustment pin is fully locked before lifting.',
            ],
            [
                'name' => 'Resistance Band Kit',
                'category' => 'Accessories',
                'brand' => 'AUREX',
                'model' => 'Band Pack',
                'serial_number' => 'AUX-EQ-0007',
                'location' => 'Functional Area',
                'primary_muscle_group' => 'Full Body',
                'secondary_muscle_group' => 'Core',
                'supported_level' => 'Beginner',
                'linked_exercises' => 18,
                'purchase_price' => 180000,
                'status' => 'Active',
                'maintenance_priority' => 'Low',
                'description' => 'Set of resistance bands for mobility, activation and strength work.',
                'safety_instructions' => 'Check bands for tears before stretching under load.',
            ],
            [
                'name' => 'Kettlebell Set',
                'category' => 'Free Weights',
                'brand' => 'Rogue',
                'model' => 'Competition 8-32kg',
                'serial_number' => 'AUX-EQ-0008',
                'location' => 'Functional Area',
                'primary_muscle_group' => 'Full Body',
                'secondary_muscle_group' => 'Core',
                'supported_level' => 'Intermediate',
                'linked_exercises' => 26,
                'purchase_price' => 2400000,
                'status' => 'Active',
                'maintenance_priority' => 'Low',
                'description' => 'Competition kettlebells for swings, cleans, presses and carries.',
                'safety_instructions' => 'Keep the training area clear before dynamic movements.',
            ],
        ];

        foreach ($equipment as $item) {
            Equipment::updateOrCreate(
                ['serial_number' => $item['serial_number']],
                [
                    'purchase_date' => now()->subMonths(8)->toDateString(),
                    'last_service_date' => now()->subMonth()->toDateString(),
                    'next_service_date' => now()->addMonths(2)->toDateString(),
                    'show_in_mobile_app' => true,
                    'access_type' => 'Members Only',
                    'publish_status' => 'Published',
                    ...$item,
                ],
            );
        }
    }
}
