<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [
            [
                'name' => 'Shoulder Press Machine',
                'category' => 'Equipment Based',
                'body_part' => 'Shoulders',
                'equipment' => 'Machine',
                'workout_level' => 'Beginner',
                'duration' => '10 min',
                'sets' => '3 sets',
                'reps' => '10-12 reps',
                'rest_time' => '60 sec',
                'description' => 'Controlled seated pressing movement for shoulder strength.',
                'instructions' => [
                    'Adjust the seat so handles start near shoulder height.',
                    'Keep your back flat against the pad.',
                    'Press the handles upward without locking your elbows hard.',
                    'Lower the handles slowly back to the starting position.',
                ],
                'muscle_tags' => ['Shoulders', 'Triceps', 'Upper Chest'],
            ],
            [
                'name' => 'Leg Press',
                'category' => 'Equipment Based',
                'body_part' => 'Legs',
                'equipment' => 'Machine',
                'workout_level' => 'Beginner',
                'duration' => '12 min',
                'sets' => '4 sets',
                'reps' => '10-15 reps',
                'rest_time' => '90 sec',
                'description' => 'Lower-body compound exercise targeting quads, glutes and hamstrings.',
                'instructions' => [
                    'Place feet shoulder-width apart on the platform.',
                    'Release the safety handles and lower the platform with control.',
                    'Stop before your lower back lifts from the pad.',
                    'Push through your heels to return to the start.',
                ],
                'muscle_tags' => ['Quads', 'Glutes', 'Hamstrings'],
            ],
            [
                'name' => 'Lat Pulldown',
                'category' => 'Equipment Based',
                'body_part' => 'Back',
                'equipment' => 'Machine',
                'workout_level' => 'Beginner',
                'duration' => '10 min',
                'sets' => '3 sets',
                'reps' => '10-12 reps',
                'rest_time' => '60 sec',
                'description' => 'Upper-back pulling movement for lat and biceps development.',
                'instructions' => [
                    'Grip the bar slightly wider than shoulder width.',
                    'Sit tall with thighs secured under the pads.',
                    'Pull the bar toward your upper chest.',
                    'Return the bar upward slowly with control.',
                ],
                'muscle_tags' => ['Lats', 'Biceps', 'Upper Back'],
            ],
            [
                'name' => 'Dumbbell Bench Press',
                'category' => 'Equipment Based',
                'body_part' => 'Chest',
                'equipment' => 'Dumbbell',
                'workout_level' => 'Intermediate',
                'duration' => '12 min',
                'sets' => '4 sets',
                'reps' => '8-12 reps',
                'rest_time' => '90 sec',
                'description' => 'Chest press variation that improves pressing strength and stability.',
                'instructions' => [
                    'Lie on a flat bench with dumbbells beside the chest.',
                    'Keep feet planted and shoulder blades pulled back.',
                    'Press the dumbbells upward in a controlled path.',
                    'Lower until elbows are slightly below shoulder level.',
                ],
                'muscle_tags' => ['Chest', 'Triceps', 'Shoulders'],
            ],
            [
                'name' => 'Goblet Squat',
                'category' => 'Equipment Based',
                'body_part' => 'Legs',
                'equipment' => 'Kettlebell',
                'workout_level' => 'Beginner',
                'duration' => '8 min',
                'sets' => '3 sets',
                'reps' => '12-15 reps',
                'rest_time' => '60 sec',
                'description' => 'Beginner-friendly squat pattern using a kettlebell or dumbbell.',
                'instructions' => [
                    'Hold the weight close to your chest.',
                    'Stand with feet just outside hip width.',
                    'Squat down while keeping your chest tall.',
                    'Drive through the floor to stand back up.',
                ],
                'muscle_tags' => ['Quads', 'Glutes', 'Core'],
            ],
            [
                'name' => 'Push Up',
                'category' => 'Body Part Exercise',
                'body_part' => 'Chest',
                'equipment' => 'No Equipment',
                'workout_level' => 'Beginner',
                'duration' => '8 min',
                'sets' => '3 sets',
                'reps' => '8-15 reps',
                'rest_time' => '45 sec',
                'description' => 'Bodyweight pressing exercise for chest, shoulders and triceps.',
                'instructions' => [
                    'Start in a high plank with hands under shoulders.',
                    'Keep your body straight from head to heels.',
                    'Lower your chest toward the floor.',
                    'Press back up without letting hips sag.',
                ],
                'muscle_tags' => ['Chest', 'Triceps', 'Core'],
            ],
            [
                'name' => 'Plank Hold',
                'category' => 'Body Part Exercise',
                'body_part' => 'Abs',
                'equipment' => 'No Equipment',
                'workout_level' => 'Beginner',
                'duration' => '6 min',
                'sets' => '3 sets',
                'reps' => '30-60 sec',
                'rest_time' => '45 sec',
                'description' => 'Core stability exercise that strengthens the trunk and posture.',
                'instructions' => [
                    'Place elbows under shoulders.',
                    'Brace your core and squeeze glutes.',
                    'Keep your back flat and neck neutral.',
                    'Hold for the assigned time.',
                ],
                'muscle_tags' => ['Core', 'Abs', 'Stabilizers'],
            ],
            [
                'name' => 'Resistance Band Row',
                'category' => 'Body Part Exercise',
                'body_part' => 'Back',
                'equipment' => 'Resistance Bands',
                'workout_level' => 'Beginner',
                'duration' => '8 min',
                'sets' => '3 sets',
                'reps' => '12-15 reps',
                'rest_time' => '45 sec',
                'description' => 'Band row variation for back activation and posture.',
                'instructions' => [
                    'Anchor the band securely at chest height.',
                    'Hold both handles with arms extended.',
                    'Pull elbows back and squeeze shoulder blades.',
                    'Return slowly without losing tension.',
                ],
                'muscle_tags' => ['Back', 'Rear Delts', 'Biceps'],
            ],
            [
                'name' => 'Treadmill Intervals',
                'category' => 'Workout',
                'body_part' => 'Full Body',
                'equipment' => 'Machine',
                'workout_level' => 'Intermediate',
                'duration' => '20 min',
                'sets' => '8 rounds',
                'reps' => '30 sec fast / 90 sec easy',
                'rest_time' => '90 sec',
                'description' => 'Cardio interval session for conditioning and calorie burn.',
                'instructions' => [
                    'Warm up with a light jog for five minutes.',
                    'Run fast for thirty seconds.',
                    'Recover with an easy walk or jog for ninety seconds.',
                    'Repeat for the assigned number of rounds.',
                ],
                'muscle_tags' => ['Cardio', 'Legs', 'Endurance'],
            ],
            [
                'name' => 'Kettlebell Swing',
                'category' => 'Workout',
                'body_part' => 'Full Body',
                'equipment' => 'Kettlebell',
                'workout_level' => 'Advanced',
                'duration' => '10 min',
                'sets' => '5 sets',
                'reps' => '15-20 reps',
                'rest_time' => '60 sec',
                'description' => 'Explosive hip-hinge movement for power and conditioning.',
                'instructions' => [
                    'Stand with the kettlebell slightly in front of you.',
                    'Hinge at the hips and grip the handle.',
                    'Drive hips forward to swing the kettlebell to chest height.',
                    'Let it return between the legs while maintaining a flat back.',
                ],
                'muscle_tags' => ['Glutes', 'Hamstrings', 'Core'],
            ],
        ];

        foreach ($exercises as $exercise) {
            Exercise::updateOrCreate(
                ['name' => $exercise['name']],
                [
                    'status' => 'Active',
                    'show_in_mobile_app' => true,
                    'access_type' => 'Members Only',
                    'publish_status' => 'Published',
                    ...$exercise,
                ],
            );
        }
    }
}
