<?php

namespace Database\Seeders;

use App\Models\Trainer;
use Illuminate\Database\Seeder;

class TrainerSeeder extends Seeder
{
    public function run(): void
    {
        $trainers = [
            [
                'full_name' => 'Coach Daniel',
                'phone' => '+255 712 345 678',
                'email' => 'daniel@aurex.test',
                'gender' => 'Male',
                'specialty' => 'Strength Training',
                'experience' => '7 years',
                'certification' => 'ACE Strength & Conditioning',
                'status' => 'Active',
                'assigned_classes' => 12,
                'assigned_clients' => 34,
                'rating' => 4.9,
                'bio' => 'Strength coach focused on progressive overload, compound lifts and athlete conditioning.',
                'availability_days' => ['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday'],
                'start_time' => '06:00',
                'end_time' => '14:00',
                'payment_type' => 'Monthly Salary',
                'rate_amount' => 1200000,
                'payment_method' => 'Bank Transfer',
                'payment_reference' => 'AUREX-DANIEL-001',
                'role' => 'Senior Trainer',
            ],
            [
                'full_name' => 'Coach Sarah',
                'phone' => '+255 713 222 111',
                'email' => 'sarah@aurex.test',
                'gender' => 'Female',
                'specialty' => 'HIIT & Weight Loss',
                'experience' => '6 years',
                'certification' => 'NASM Certified Personal Trainer',
                'status' => 'Active',
                'assigned_classes' => 9,
                'assigned_clients' => 28,
                'rating' => 4.8,
                'bio' => 'Transformation coach specializing in HIIT, weight loss and lifestyle adherence.',
                'availability_days' => ['Monday', 'Wednesday', 'Thursday', 'Friday', 'Sunday'],
                'start_time' => '10:00',
                'end_time' => '19:00',
                'payment_type' => 'Monthly Salary',
                'rate_amount' => 1100000,
                'payment_method' => 'M-Pesa',
                'payment_reference' => '+255713222111',
                'role' => 'Senior Trainer',
            ],
            [
                'full_name' => 'Coach Michael',
                'phone' => '+255 765 909 404',
                'email' => 'michael@aurex.test',
                'gender' => 'Male',
                'specialty' => 'Beginner Fitness',
                'experience' => '4 years',
                'certification' => 'Level 2 Fitness Instructor',
                'status' => 'Active',
                'assigned_classes' => 6,
                'assigned_clients' => 18,
                'rating' => 4.6,
                'bio' => 'Beginner-friendly coach helping new members learn movement basics safely.',
                'availability_days' => ['Tuesday', 'Thursday', 'Saturday'],
                'start_time' => '08:00',
                'end_time' => '16:00',
                'payment_type' => 'Per Class',
                'rate_amount' => 30000,
                'payment_method' => 'Cash',
                'payment_reference' => 'Reception payout',
                'role' => 'Trainer',
            ],
            [
                'full_name' => 'Coach Amina',
                'phone' => '+255 744 333 888',
                'email' => 'amina@aurex.test',
                'gender' => 'Female',
                'specialty' => 'Cardio',
                'experience' => '5 years',
                'certification' => 'Group Fitness Instructor',
                'status' => 'Active',
                'assigned_classes' => 8,
                'assigned_clients' => 22,
                'rating' => 4.7,
                'bio' => 'Group fitness coach leading cardio, endurance and mobility sessions.',
                'availability_days' => ['Monday', 'Tuesday', 'Thursday', 'Sunday'],
                'start_time' => '07:00',
                'end_time' => '15:00',
                'payment_type' => 'Per Class',
                'rate_amount' => 35000,
                'payment_method' => 'M-Pesa',
                'payment_reference' => '+255744333888',
                'role' => 'Trainer',
            ],
            [
                'full_name' => 'Coach Peter',
                'phone' => '+255 755 101 202',
                'email' => 'peter@aurex.test',
                'gender' => 'Male',
                'specialty' => 'Bodybuilding',
                'experience' => '9 years',
                'certification' => 'Bodybuilding Prep Specialist',
                'status' => 'On Leave',
                'assigned_classes' => 4,
                'assigned_clients' => 15,
                'rating' => 4.8,
                'bio' => 'Bodybuilding coach focused on hypertrophy, posing and contest preparation.',
                'availability_days' => ['Wednesday', 'Friday', 'Saturday'],
                'start_time' => '15:00',
                'end_time' => '21:00',
                'payment_type' => 'Per Client',
                'rate_amount' => 50000,
                'payment_method' => 'Bank Transfer',
                'payment_reference' => 'AUREX-PETER-005',
                'role' => 'Head Coach',
            ],
            [
                'full_name' => 'Coach Neema',
                'phone' => '+255 789 555 222',
                'email' => 'neema@aurex.test',
                'gender' => 'Female',
                'specialty' => 'Nutrition Coach',
                'experience' => '5 years',
                'certification' => 'Sports Nutrition Certificate',
                'status' => 'Active',
                'assigned_classes' => 3,
                'assigned_clients' => 31,
                'rating' => 4.9,
                'bio' => 'Nutrition coach supporting fat loss, muscle gain and performance meal planning.',
                'availability_days' => ['Monday', 'Wednesday', 'Friday'],
                'start_time' => '09:00',
                'end_time' => '17:00',
                'payment_type' => 'Commission',
                'rate_amount' => 20,
                'payment_method' => 'Bank Transfer',
                'payment_reference' => 'AUREX-NEEMA-006',
                'role' => 'Trainer',
            ],
        ];

        foreach ($trainers as $trainer) {
            Trainer::updateOrCreate(
                ['email' => $trainer['email']],
                [
                    'date_of_birth' => now()->subYears(30)->toDateString(),
                    'address' => 'Arusha, Tanzania',
                    'allow_dashboard_login' => false,
                    'trainer_app_access' => true,
                    ...$trainer,
                ],
            );
        }
    }
}
