<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AppBannerController;
use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\BodyPartController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\DietPlanController;
use App\Http\Controllers\Api\EquipmentController;
use App\Http\Controllers\Api\ExerciseController;
use App\Http\Controllers\Api\GymClassController;
use App\Http\Controllers\Api\MemberController;
use App\Http\Controllers\Api\MembershipPlanController;
use App\Http\Controllers\Api\MobileAppController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\TrainerController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\WorkoutController;
use App\Http\Controllers\Api\WorkoutLevelController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login']);

Route::middleware('api.token')->group(function () {
    Route::get('/me', [AuthController::class, 'me']);
    Route::put('/profile', [AuthController::class, 'updateProfile']);
    Route::post('/profile/photo', [AuthController::class, 'updateProfilePhoto']);
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::post('/change-password', [AuthController::class, 'changePassword']);
    Route::get('/dashboard', [DashboardController::class, 'show']);
    Route::get('/settings', [SettingController::class, 'show']);
    Route::put('/settings', [SettingController::class, 'update']);
    Route::get('/membership-plans', [MembershipPlanController::class, 'index']);
    Route::post('/membership-plans', [MembershipPlanController::class, 'store']);
    Route::get('/membership-plans/{membershipPlan}', [MembershipPlanController::class, 'show']);
    Route::put('/membership-plans/{membershipPlan}', [MembershipPlanController::class, 'update']);
    Route::delete('/membership-plans/{membershipPlan}', [MembershipPlanController::class, 'destroy']);
    Route::get('/members', [MemberController::class, 'index']);
    Route::post('/members', [MemberController::class, 'store']);
    Route::get('/members/{member}', [MemberController::class, 'show']);
    Route::put('/members/{member}', [MemberController::class, 'update']);
    Route::delete('/members/{member}', [MemberController::class, 'destroy']);
    Route::get('/payments', [PaymentController::class, 'index']);
    Route::post('/payments', [PaymentController::class, 'store']);
    Route::get('/payments/{payment}', [PaymentController::class, 'show']);
    Route::delete('/payments/{payment}', [PaymentController::class, 'destroy']);
    Route::get('/reports', [ReportController::class, 'index']);
    Route::get('/attendance', [AttendanceController::class, 'index']);
    Route::post('/attendance', [AttendanceController::class, 'store']);
    Route::post('/attendance/{attendance}/checkout', [AttendanceController::class, 'checkout']);
    Route::get('/attendance-members', [AttendanceController::class, 'members']);
    Route::get('/equipment', [EquipmentController::class, 'index']);
    Route::post('/equipment', [EquipmentController::class, 'store']);
    Route::get('/equipment/{equipment}', [EquipmentController::class, 'show']);
    Route::put('/equipment/{equipment}', [EquipmentController::class, 'update']);
    Route::delete('/equipment/{equipment}', [EquipmentController::class, 'destroy']);
    Route::get('/body-parts', [BodyPartController::class, 'index']);
    Route::post('/body-parts', [BodyPartController::class, 'store']);
    Route::get('/body-parts/{bodyPart}', [BodyPartController::class, 'show']);
    Route::put('/body-parts/{bodyPart}', [BodyPartController::class, 'update']);
    Route::delete('/body-parts/{bodyPart}', [BodyPartController::class, 'destroy']);
    Route::get('/exercises', [ExerciseController::class, 'index']);
    Route::post('/exercises', [ExerciseController::class, 'store']);
    Route::get('/exercises/{exercise}', [ExerciseController::class, 'show']);
    Route::put('/exercises/{exercise}', [ExerciseController::class, 'update']);
    Route::delete('/exercises/{exercise}', [ExerciseController::class, 'destroy']);
    Route::get('/workout-levels', [WorkoutLevelController::class, 'index']);
    Route::post('/workout-levels', [WorkoutLevelController::class, 'store']);
    Route::get('/workout-levels/{workoutLevel}', [WorkoutLevelController::class, 'show']);
    Route::put('/workout-levels/{workoutLevel}', [WorkoutLevelController::class, 'update']);
    Route::delete('/workout-levels/{workoutLevel}', [WorkoutLevelController::class, 'destroy']);
    Route::get('/workouts', [WorkoutController::class, 'index']);
    Route::post('/workouts', [WorkoutController::class, 'store']);
    Route::get('/workouts/{workout}', [WorkoutController::class, 'show']);
    Route::put('/workouts/{workout}', [WorkoutController::class, 'update']);
    Route::delete('/workouts/{workout}', [WorkoutController::class, 'destroy']);
    Route::get('/mobile-app', [MobileAppController::class, 'show']);
    Route::get('/app-banners', [AppBannerController::class, 'index']);
    Route::post('/app-banners', [AppBannerController::class, 'store']);
    Route::get('/app-banners/{appBanner}', [AppBannerController::class, 'show']);
    Route::put('/app-banners/{appBanner}', [AppBannerController::class, 'update']);
    Route::delete('/app-banners/{appBanner}', [AppBannerController::class, 'destroy']);
    Route::get('/diet-plans', [DietPlanController::class, 'index']);
    Route::post('/diet-plans', [DietPlanController::class, 'store']);
    Route::get('/diet-plans/{dietPlan}', [DietPlanController::class, 'show']);
    Route::put('/diet-plans/{dietPlan}', [DietPlanController::class, 'update']);
    Route::delete('/diet-plans/{dietPlan}', [DietPlanController::class, 'destroy']);
    Route::get('/classes', [GymClassController::class, 'index']);
    Route::post('/classes', [GymClassController::class, 'store']);
    Route::get('/classes/{class}', [GymClassController::class, 'show']);
    Route::put('/classes/{class}', [GymClassController::class, 'update']);
    Route::delete('/classes/{class}', [GymClassController::class, 'destroy']);
    Route::get('/trainers', [TrainerController::class, 'index']);
    Route::post('/trainers', [TrainerController::class, 'store']);
    Route::get('/trainers/{trainer}', [TrainerController::class, 'show']);
    Route::put('/trainers/{trainer}', [TrainerController::class, 'update']);
    Route::delete('/trainers/{trainer}', [TrainerController::class, 'destroy']);
    Route::get('/users', [UserController::class, 'index']);
    Route::post('/users', [UserController::class, 'store']);
    Route::get('/users/{user}', [UserController::class, 'show']);
    Route::put('/users/{user}', [UserController::class, 'update']);
    Route::delete('/users/{user}', [UserController::class, 'destroy']);
    Route::post('/users/{user}/reset-password', [UserController::class, 'resetPassword']);
});
